### --------------------------------------
### Docker-compose
### Angel Valera Motos - P2 - CC 
### --------------------------------------
###
version: '3'

volumes:
  files:
    driver: local
  mysql:
    driver: local
  backup:
    driver: local 

services:
  # Servicio con base de datos MariaDB 
  MariaDB:
    image: webhippie/mariadb:latest
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=master
      - MARIADB_USERNAME=angelvm
      - MARIADB_PASSWORD=003577
      - MARIADB_DATABASE=SanFrancisco
      - MARIADB_MAX_ALLOWED_PACKET=128M
      - MARIADB_INNODB_LOG_FILE_SIZE=64M
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - mysql:/var/lib/mysql
      - backup:/var/lib/backup

  version1:
    build: /tmp/workflow/servicioV1/
    command: gunicorn app:app -b :4000
    environment:
      - HOST=MariaDB
    ports:
      - 4000:4000
    links: 
      - MariaDB
  

